### ISSUE TITLE
can't preview project

### ISSUE THREAD

**Issue by wprayudo** [totaljs/code#2]
I try create project and click preview, then the address URL get http://my_host:port/my_project , but it return editor view in new tab and I get logout

**Comment by petersirka** [comment]
Hi, sorry for delay I forgot to answer. Do you mean in Electron version?

**Comment by wprayudo** [comment]
web version

**Comment by petersirka** [comment]
Do you mean this button? If yes then it works correctly (I have tested it). 

![image](https://user-images.githubusercontent.com/2414252/51798887-e7ccdb80-2219-11e9-9f34-0b0e46270bef.png)

BTW: try to download test version, I have added new improvements.

**Comment by wprayudo** [comment]
![image](https://user-images.githubusercontent.com/1198588/51798925-e49f1300-224c-11e9-9865-25e821f891c8.png)

yes, it is. and always got this. or did I set wrong url at settings?

**Comment by wprayudo** [comment]
and I've logout too 
![image](https://user-images.githubusercontent.com/1198588/51798950-41023280-224d-11e9-9bfa-3f76d1990da6.png)

**Comment by petersirka** [comment]
Show me your project setting.

**Comment by petersirka** [comment]
Of course, you need to add absolute URL address with a protocol, for example `https://dashboard.com`.

**Comment by wprayudo** [comment]
ah you're right. thanks a lot
