### ISSUE TITLE
Stuck on loading 

### ISSUE THREAD

**Issue by punters360** [totaljs/code#5]
Hey guys i have noticed with v1.4.0 when you save a file it does save the file but the screen just gets stuck on the loading and nevers comes off until you refresh the page ?? 

cdn.min.js:13 POST http://103.16.131.178:8000/api/files/197682001ap61b/ 408 (Request Timeout)

getting this error ?? 

also with the new v5 you cant seem to add a new directory to the project ?

**Comment by petersirka** [comment]
There is a problem on the server-side. Check the application logs because there will be some exception.

> also with the new v5 you cant seem to add a new directory to the project ?

New features are part of branch `total4`. You can use it without any problem, but you need to install Total.js 4 `$ npm install total4`.

**Comment by punters360** [comment]
Can you give me some more direction with using version 5 ?   I have installed total4 but how i use the code editor ? is total4 the code editor ? or is it some other program needed to run the editor ?

**Comment by petersirka** [comment]
https://github.com/totaljs/code/tree/total4

- download source-code of Code branch `total4`
- perform `$ npm install`
- run code:
  - `$ cd code`
  - `$ node index.js`
- open `http://127.0.0.1:8000`

---

Do you have some Total.js Cloud container in our cloud?

**Comment by punters360** [comment]
ok so npm is installed and I have installed total4 into the dir that the total code v5 is in  I run the index.js file and i get this back 

 Error: Cannot find module 'total4/debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/punters360/totaljs_code160/index.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by punters360** [comment]
when i run the debug.js or release.js file it seems to run but i get errors when im trying to add a new repository it errors out 

<img width="1693" alt="Screenshot_3" src="https://user-images.githubusercontent.com/62288052/84867080-ff7e5b80-b0bd-11ea-99f1-ddda4ba20e63.png">

**Comment by molda** [comment]
Make sure you have installed total4@beta. If you installed framework using `npm install total4` then reinstall it using `npm install total4@beta`
You can check `./node_modules/total4/` folder and if there's only index.js and package.json then that's the problem.

**Comment by punters360** [comment]
Cool!! that solved that problem now its working however i still have the same original problem stock on loading screen when i save a file 

<img width="1813" alt="Screenshot_4" src="https://user-images.githubusercontent.com/62288052/84868187-a57e9580-b0bf-11ea-920a-65a2b41d4800.png">

**Comment by molda** [comment]
Any error on the server?

**Comment by punters360** [comment]
its got something to do with running on port 8000 how can i change the config to boot it on another port  ?

**Comment by molda** [comment]
config

default_port   : 8001

**Comment by punters360** [comment]
ok got the port to change but it did not resolve the problem still a post timeout error when saving a file ??

**Comment by petersirka** [comment]
Port can be changed easily via `$ node index.js 8005` ... But we need to see application logs.

**Comment by punters360** [comment]
The application logs will not load anything ??   what other logs can i check ?

**Comment by molda** [comment]
In the screenshot you posted above there's also `500 Internal server error' before the timeout error. You should see that error on the server with full stack.

**Comment by petersirka** [comment]
> what other logs can i check ?

Check the output from terminal, there are logs.

**Comment by punters360** [comment]
now its doing Evan stranger things when you open a file 

<img width="1890" alt="Screenshot_5" src="https://user-images.githubusercontent.com/62288052/84875419-4b82cd80-b0c9-11ea-9059-1b18bd6da111.png">

**Comment by punters360** [comment]
Server logs 


<img width="715" alt="jfkdla" src="https://user-images.githubusercontent.com/62288052/84877207-884fc400-b0cb-11ea-9ff2-8be78aa94862.PNG">


<img width="959" alt="jfkdlajkl" src="https://user-images.githubusercontent.com/62288052/84877111-62c2ba80-b0cb-11ea-9ab0-01fbd1ff342e.PNG">

**Comment by molda** [comment]
`Permision denied` is quite obvius error. You don't have permision to create /www directory.
What directory is the application you are editing in?
Have you changed `backup` config?

**Comment by punters360** [comment]
everything is obvious when you know how,  we still carnt seem to get this to work can you give us more direction ?

**Comment by molda** [comment]
The error from the screenshot above has nothing to do with Total.js framework or Code application.
It has something to do with `pm2` process manager. We can't help you with that.

**Comment by punters360** [comment]
But these are logs generated from pm2 running totaljs  how is this not relevant ? 

what other logs do you want me to show you ???  im asking for help here guys.....

**Comment by petersirka** [comment]
We don't use PM2, we recommend to use Total.js Cloud or Total.js SuperAdmin. Total.js is not optimized for PM2.

> what other logs do you want me to show you ??? im asking for help here guys.....

We requrested for logs from Total.js application, not from PM2.  We need to see where is the problem in Total.js. @molda described the problem -> `Permision denied is quite obvious error`.

**Comment by punters360** [comment]
but Evan if we dont use PM2 we get the same problem no matter how we run it it gets the same thing ??

if we cannot get this running do you guys know of any other self hosting online editors we could try ?

**Comment by petersirka** [comment]
You can test Total.js Code Editor easily in Total.js Cloud for free for 48 hours (after that is container removed) or rent some virtual server and install SuperAdmin and then install Total.js Code.

> but Evan if we dont use PM2 we get the same problem no matter how we run it it gets the same thing ??

No, you can run it directly via:

```bash
$ cd code
$ node index.js
```

Then you will see all logs from the app directly in terminal.

**Comment by punters360** [comment]
I seem to be not getting my message across.    so if I run it using cd code node index.js   which just runs the debug version   it still has the same problem.   

with running superadmin on a virtual server to you mean a complete new server ?  as in rent a new box and install it on that ???   what is superadmin ?  cant i just run it all on one server ?

**Comment by petersirka** [comment]
> runs the debug version it still has the same problem

With privileges? Show logs.

__SuperAdmin__ installation:

```bash
# UBUNTU
$ sudo wget https://cdn.totaljs.com/superadmin.sh && bash superadmin.sh
```

```bash
# CENTOS
$ sudo wget https://cdn.totaljs.com/superadmin-centos.sh && bash superadmin-centos.sh
```

```bash
# ALPINE
$ sudo wget https://cdn.totaljs.com/superadmin-alpine.sh && bash superadmin-alpine.sh
```

Or you can use the best way for development - **Total.js Cloud**:
- https://platform.totaljs.com
- you can start to code in 2 minutes in Total.js Code Editor

**Comment by punters360** [comment]
We are a startup and need to watch spending.   

its a shame we cant get it working non of your replys are help full I think we will just look for some other online editor that works.    thanks anyway

**Comment by molda** [comment]
I'm sorry to hear it still doesn't work for you.
I just tried the simplest way to run the editor using following steps

For master branch
- `git clone https://github.com/totaljs/code.git`
- `cd code`
- `npm i`
- `node debug.js`


For total4 branch which is most recent officialy unreleased version
- `git clone https://github.com/totaljs/code.git`
- `cd code`
- `git checkout total4`
- `npm i`
- `node index.js`

Both worked except for creating directories which i fixed by creating

**Comment by molda** [comment]
I'm sorry to hear it still doesn't work for you.
I just tried the simplest way to run the editor using following steps

For master branch

- `git clone https://github.com/totaljs/code.git`
- `cd code`
- `npm i`
- `node debug.js`

For total4 branch which is most recent officialy unreleased version

- `git clone https://github.com/totaljs/code.git`
- `cd code`
- `git checkout total4`
- `npm i`
- `node index.js`

Default folder for backups is /www/tmp/backup/ which must exist and process(Code app) must have write permision.

I had no issues with it at all.

**Comment by punters360** [comment]
The total4 is the in home directory of our server. 

But how do i change the permissions so that total4 has root permissions ? 

The problem is not downloading and installing the app or getting it running the problem is it wont save 

so lets focus on how we can solve this.  its like you said, a permissions issue but i dont know how to solve it.

**Comment by molda** [comment]
If the Code app is running in your home directory and the code you are editing is also in your home directory then just change the backup path in config file to also point somewhere in your home dir and you don't need to run it as root. You should have no problem with permisions.
If you still have issues then please answer these questions.
- Where is the Code app installed? for example: /home/punters360/codeapp/
- Where are the files you edit? for example /home/punters360/applications/
- What is `backup` config set to? See config file in the root of Code app to find out. Ideally set to /home/punters360/backup/ or anywhere in your home directory to avoid permisions issues
- What is the path in Projects for each of your apps? for example /home/punters360/applications/app1 Make sure to use absolute paths !!!

**Comment by punters360** [comment]
**Where is the Code app installed? for example: /home/punters360/codeapp/**
the code app is installed at /home/punters360/totaljs_code160

**Where are the files you edit? for example /home/punters360/applications/**
/home/punters360/node_website_react

**What is backup config set to?** 
This is my config app below 
______________________________________________
name                  : Code
allow_custom_titles   : true

cookie                : __sauth
authkey               : seEdCollabo

backup                : /home/punters360/backup/
autodiscover          : /www/www/

default_port : 8008

______________________________________________

**What is the path in Projects for each of your apps?**
/home/punters360/node_website_react
/home/punters360/node_socialserver
/home/punters360/node_betserver

I Run the app under sudo command: sudo node debug.js  

and we still cannot save a file giving timeout requests stuck on loading screen still ???

**Comment by molda** [comment]
This all looks good. I don't see a reason for it to fail at creating directories.
It would be helpfull if you can show me more of the totaljs-out.log 
You shouldn't even need to run Code as root with sudo since everything is in your home directory.

**Comment by punters360** [comment]
Do you have a skype contact and maybe you could fix it for me ?? I will pay you ?
